"""Unified primary offline APIs plus source-compatible and explicit legacy entries."""

from .api import (
    OfflineInspectionError,
    OfflineRunRecord,
    approve_legacy_v1_strategy,
    approve_strategy,
    build_intent_communication_service,
    capabilities,
    inspect_legacy_v1_offline,
    inspect_legacy_v2_offline,
    inspect_offline,
    inspect_offline_auto,
    publish_legacy_v1_strategy,
    publish_strategy,
    query_legacy_v1_strategies,
    query_strategies,
    run_legacy_v1_offline,
    run_legacy_v1_request,
    run_legacy_v2_request,
    run_offline,
    run_summary,
    run_summary_legacy_v1,
    run_summary_legacy_v2,
    run_unified_offline,
    validate_intent_file,
    validate_legacy_v1_request,
    validate_legacy_v2_request,
    validate_problem_files,
)
from .chat_summary import (
    ChatCompatibleRunRecord,
    build_chat_operating_status,
    build_chat_result_summary,
)

__all__ = [
    "ChatCompatibleRunRecord",
    "OfflineInspectionError",
    "OfflineRunRecord",
    "approve_legacy_v1_strategy",
    "approve_strategy",
    "build_chat_operating_status",
    "build_chat_result_summary",
    "build_intent_communication_service",
    "capabilities",
    "inspect_legacy_v1_offline",
    "inspect_legacy_v2_offline",
    "inspect_offline",
    "inspect_offline_auto",
    "publish_legacy_v1_strategy",
    "publish_strategy",
    "query_legacy_v1_strategies",
    "query_strategies",
    "run_legacy_v1_offline",
    "run_legacy_v1_request",
    "run_legacy_v2_request",
    "run_offline",
    "run_summary",
    "run_summary_legacy_v1",
    "run_summary_legacy_v2",
    "run_unified_offline",
    "validate_intent_file",
    "validate_legacy_v1_request",
    "validate_legacy_v2_request",
    "validate_problem_files",
]
