"""Public runtime surface for the offline RTO workflow."""

from ..contracts.context import OperatingContext
from ..progress import RtoProgress, RtoProgressCallback
from .api import (
    OfflineInspectionError,
    OfflineRunRecord,
    approve_strategy,
    build_intent_communication_service,
    capabilities,
    inspect_offline,
    publish_strategy,
    query_strategies,
    run_confirmed_optimization,
    run_offline,
    run_summary,
    validate_intent_file,
    validate_problem_files,
)
from .chat_summary import (
    OptimizationAdjustmentSummary,
    OptimizationAlternativeCandidateSummary,
    OptimizationBaselineSummary,
    OptimizationContextSummary,
    OptimizationPredictedEffectSummary,
    OptimizationRunSummary,
    OptimizationTargetSummary,
    build_chat_operating_status,
    build_optimization_run_summary,
)

__all__ = [
    "OfflineInspectionError",
    "OfflineRunRecord",
    "OperatingContext",
    "OptimizationAdjustmentSummary",
    "OptimizationAlternativeCandidateSummary",
    "OptimizationBaselineSummary",
    "OptimizationContextSummary",
    "OptimizationPredictedEffectSummary",
    "OptimizationPreparationError",
    "OptimizationRunSummary",
    "OptimizationTargetSummary",
    "PreparedOptimization",
    "RtoProgress",
    "RtoProgressCallback",
    "approve_strategy",
    "build_chat_operating_status",
    "build_intent_communication_service",
    "build_optimization_run_summary",
    "capabilities",
    "dump_prepared_optimization",
    "inspect_offline",
    "load_prepared_optimization",
    "prepare_optimization",
    "publish_strategy",
    "query_strategies",
    "read_prepared_result",
    "read_prepared_static",
    "render_confirmation",
    "run_confirmed_optimization",
    "run_offline",
    "run_summary",
    "solve_prepared_optimization",
    "validate_intent_file",
    "validate_problem_files",
    "verify_prepared_optimization",
]

from .staged import (
    OptimizationPreparationError,
    PreparedOptimization,
    dump_prepared_optimization,
    load_prepared_optimization,
    prepare_optimization,
    read_prepared_result,
    read_prepared_static,
    render_confirmation,
    solve_prepared_optimization,
    verify_prepared_optimization,
)
