"""Public protocol boundary for a future vertical-domain model."""

from ..contracts.reference import ContractRef
from ..unified_inputs import OptimizationIntent
from .factory import build_intent_communication_service
from .invocation import (
    DOMAIN_MODEL_INVOCATION_RESULT_SCHEMA_ID,
    MAX_DOMAIN_MODEL_OUTPUT_BYTES,
    DomainModelInvocationResult,
    DomainModelInvocationStatus,
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderError,
    ProviderErrorCategory,
    ProviderUsage,
)
from .loader import decode_domain_model_response
from .models import (
    COMMUNICATION_RESULT_SCHEMA_ID,
    COMMUNICATION_SCHEMA_VERSION,
    DOMAIN_CAPABILITY_MANIFEST_SCHEMA_ID,
    DOMAIN_CAPABILITY_MANIFEST_SCHEMA_VERSION,
    DOMAIN_MODEL_REQUEST_SCHEMA_ID,
    DOMAIN_MODEL_REQUEST_SCHEMA_VERSION,
    DOMAIN_MODEL_RESPONSE_SCHEMA_ID,
    DOMAIN_MODEL_RESPONSE_SCHEMA_VERSION,
    DOMAIN_MODEL_UNSUPPORTED_SCHEMA_ID,
    DOMAIN_MODEL_UNSUPPORTED_SCHEMA_VERSION,
    MAX_MODEL_ATTEMPTS,
    UNSUPPORTED_SAFE_MESSAGES,
    AnswerKind,
    ClarificationAnswer,
    ClarificationOption,
    ClarificationQuestion,
    ClarificationRequest,
    CommunicationResult,
    CommunicationStatus,
    DomainCapabilityManifest,
    DomainModelRequest,
    DomainModelResponse,
    DomainModelResponseOutcome,
    DomainModelUnsupported,
    DomainOutputPolicy,
    IssueAudience,
    IssueSource,
    ProtocolIssue,
    RepairDirective,
    UnsupportedReasonCode,
    UserMessage,
)
from .policy import (
    INTENT_COMMUNICATION_POLICY_SCHEMA_ID,
    INTENT_COMMUNICATION_POLICY_SCHEMA_VERSION,
    SUPPORTED_AMBIGUITY_CODES,
    IntentCommunicationPolicy,
)
from .ports import DomainModelPort
from .service import IntentCommunicationService

__all__ = [
    "COMMUNICATION_RESULT_SCHEMA_ID",
    "COMMUNICATION_SCHEMA_VERSION",
    "DOMAIN_CAPABILITY_MANIFEST_SCHEMA_ID",
    "DOMAIN_CAPABILITY_MANIFEST_SCHEMA_VERSION",
    "DOMAIN_MODEL_INVOCATION_RESULT_SCHEMA_ID",
    "DOMAIN_MODEL_REQUEST_SCHEMA_ID",
    "DOMAIN_MODEL_REQUEST_SCHEMA_VERSION",
    "DOMAIN_MODEL_RESPONSE_SCHEMA_ID",
    "DOMAIN_MODEL_RESPONSE_SCHEMA_VERSION",
    "DOMAIN_MODEL_UNSUPPORTED_SCHEMA_ID",
    "DOMAIN_MODEL_UNSUPPORTED_SCHEMA_VERSION",
    "INTENT_COMMUNICATION_POLICY_SCHEMA_ID",
    "INTENT_COMMUNICATION_POLICY_SCHEMA_VERSION",
    "MAX_DOMAIN_MODEL_OUTPUT_BYTES",
    "MAX_MODEL_ATTEMPTS",
    "SUPPORTED_AMBIGUITY_CODES",
    "UNSUPPORTED_SAFE_MESSAGES",
    "AnswerKind",
    "ClarificationAnswer",
    "ClarificationOption",
    "ClarificationQuestion",
    "ClarificationRequest",
    "CommunicationResult",
    "CommunicationStatus",
    "ContractRef",
    "DomainCapabilityManifest",
    "DomainModelInvocationResult",
    "DomainModelInvocationStatus",
    "DomainModelPort",
    "DomainModelRequest",
    "DomainModelResponse",
    "DomainModelResponseOutcome",
    "DomainModelUnsupported",
    "DomainOutputPolicy",
    "IntentCommunicationPolicy",
    "IntentCommunicationService",
    "IssueAudience",
    "IssueSource",
    "OptimizationIntent",
    "ProtocolIssue",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderError",
    "ProviderErrorCategory",
    "ProviderUsage",
    "RepairDirective",
    "UnsupportedReasonCode",
    "UserMessage",
    "build_intent_communication_service",
    "decode_domain_model_response",
]
