"""Objective-count-neutral offline RTO public surface."""

from .capabilities import (
    BundleCapabilityView,
    CapabilityBundle,
    CapabilityCatalog,
    SystemPolicy,
    build_public_capability_manifest,
    load_capability_bundle,
)
from .compilation import CandidatePlanCompiler, CompiledPair
from .context import load_operating_context
from .contracts import (
    CandidateEvaluation,
    CandidateProposal,
    ContractRef,
    OperatingContext,
    OptimizationProblem,
    SimulationEvaluationRequest,
    SimulationPreview,
    SimulationRunBundle,
    SolverResult,
)
from .evaluation import (
    M2EvaluationService,
    M2PairedEvaluator,
    M4EvaluationService,
    M4PairedEvaluator,
)
from .intent import (
    IntentResolution,
    IntentResolver,
    OptimizationIntent,
    load_optimization_intent,
)
from .orchestration import (
    AnchorAttempt,
    AnchorValidationResult,
    OfflineRtoManifest,
    OfflineRtoOrchestrator,
    OfflineRtoRequest,
    OfflineRtoResult,
    OfflineRtoRunRecord,
    SolverExecutionArtifact,
    WorkflowEvent,
    read_offline_run,
)
from .ports import ProviderRequestFactory, SimulatorPort
from .problem import ProblemBuilder, ProblemFeatureAnalyzer
from .selection import FinalizationArtifacts, FinalSelector, PublishabilityAssessor
from .solvers import (
    CandidateEvaluatorPort,
    CoarseRefineGridSolver,
    FullGridParetoSolver,
    ProblemFeatures,
    SolverPort,
    SolverRegistry,
    SolverRouter,
    SolverRoutingDecision,
)
from .strategies import (
    StrategyAnchor,
    StrategyBuilder,
    StrategyEntry,
    StrategyLifecycleEvent,
    StrategyQuery,
    StrategyRecord,
    StrategyReleaseManifest,
    StrategyRepository,
    anchor_from_finalization,
    anchor_from_verified_candidate,
)

__all__ = [
    "AnchorAttempt",
    "AnchorValidationResult",
    "BundleCapabilityView",
    "CandidateEvaluation",
    "CandidateEvaluatorPort",
    "CandidatePlanCompiler",
    "CandidateProposal",
    "CapabilityBundle",
    "CapabilityCatalog",
    "CoarseRefineGridSolver",
    "CompiledPair",
    "ContractRef",
    "FinalSelector",
    "FinalizationArtifacts",
    "FullGridParetoSolver",
    "IntentResolution",
    "IntentResolver",
    "M2EvaluationService",
    "M2PairedEvaluator",
    "M4EvaluationService",
    "M4PairedEvaluator",
    "OfflineRtoManifest",
    "OfflineRtoOrchestrator",
    "OfflineRtoRequest",
    "OfflineRtoResult",
    "OfflineRtoRunRecord",
    "OperatingContext",
    "OptimizationIntent",
    "OptimizationProblem",
    "ProblemBuilder",
    "ProblemFeatureAnalyzer",
    "ProblemFeatures",
    "ProviderRequestFactory",
    "PublishabilityAssessor",
    "SimulationEvaluationRequest",
    "SimulationPreview",
    "SimulationRunBundle",
    "SimulatorPort",
    "SolverExecutionArtifact",
    "SolverPort",
    "SolverRegistry",
    "SolverResult",
    "SolverRouter",
    "SolverRoutingDecision",
    "StrategyAnchor",
    "StrategyBuilder",
    "StrategyEntry",
    "StrategyLifecycleEvent",
    "StrategyQuery",
    "StrategyRecord",
    "StrategyReleaseManifest",
    "StrategyRepository",
    "SystemPolicy",
    "WorkflowEvent",
    "anchor_from_finalization",
    "anchor_from_verified_candidate",
    "build_public_capability_manifest",
    "load_capability_bundle",
    "load_operating_context",
    "load_optimization_intent",
    "read_offline_run",
]
