"""Stable M7 runtime API, contracts, batch recovery and bundled resources."""

from .api import preview, run
from .artifacts import RunRecord, read_run
from .batch import (
    BATCH_MANIFEST_VERSION,
    BATCH_REQUEST_VERSION,
    BatchRecord,
    BatchRequest,
    execute_batch,
    read_batch,
    resume_batch,
)
from .contracts import (
    CUSTOM_INPUT_VERSION,
    RUN_REQUEST_VERSION,
    RUNTIME_SCHEMA_VERSION,
    RUNTIME_VERSION,
    ErrorRecord,
    EventRecord,
    ExecutionPayload,
    FailureRecord,
    RunOutcome,
    RunRequest,
    RuntimeInputEvent,
    RuntimeScenarioRequest,
    RuntimeStatus,
    RunType,
)
from .custom_inputs import (
    ResolvedRuntimeInputs,
    RuntimeInputSpec,
    list_runtime_input_specs,
    runtime_request_from_mapping,
    runtime_request_template,
)
from .presets import PRESET_IDS, RuntimePreset, list_presets, load_preset
from .resources import (
    M5RuntimeOverlay,
    RuntimeResourceBundle,
    RuntimeResourceError,
    RuntimeResourceKind,
    RuntimeResourceSpec,
    get_runtime_resource_spec,
    list_runtime_resource_ids,
    load_m5_runtime_overlay,
    load_runtime_resource_bundle,
    read_runtime_resource_bytes,
    read_runtime_resource_json,
    read_runtime_resource_text,
    runtime_resource_ids_for_preset,
    runtime_resource_sha256,
)

__all__ = [
    "BATCH_MANIFEST_VERSION",
    "BATCH_REQUEST_VERSION",
    "CUSTOM_INPUT_VERSION",
    "PRESET_IDS",
    "RUNTIME_SCHEMA_VERSION",
    "RUNTIME_VERSION",
    "RUN_REQUEST_VERSION",
    "BatchRecord",
    "BatchRequest",
    "ErrorRecord",
    "EventRecord",
    "ExecutionPayload",
    "FailureRecord",
    "M5RuntimeOverlay",
    "ResolvedRuntimeInputs",
    "RunOutcome",
    "RunRecord",
    "RunRequest",
    "RunType",
    "RuntimeInputEvent",
    "RuntimeInputSpec",
    "RuntimePreset",
    "RuntimeResourceBundle",
    "RuntimeResourceError",
    "RuntimeResourceKind",
    "RuntimeResourceSpec",
    "RuntimeScenarioRequest",
    "RuntimeStatus",
    "execute_batch",
    "get_runtime_resource_spec",
    "list_presets",
    "list_runtime_input_specs",
    "list_runtime_resource_ids",
    "load_m5_runtime_overlay",
    "load_preset",
    "load_runtime_resource_bundle",
    "preview",
    "read_batch",
    "read_run",
    "read_runtime_resource_bytes",
    "read_runtime_resource_json",
    "read_runtime_resource_text",
    "resume_batch",
    "run",
    "runtime_request_from_mapping",
    "runtime_request_template",
    "runtime_resource_ids_for_preset",
    "runtime_resource_sha256",
]
